### PR TITLE
Separate header installation

### PR DESCRIPTION
**Pull request by plummer86**
Create an install target to install the headers separate from the devtools.

### CODE REVIEW

**Comment by plummer86** [comment]
I am installing libnetconf on an embedded product where I don't need or have space for the devtools like lnctool actually installed on the product. This change gives me the ability to install only the library and headers on the product.

**Comment by rkrejci** [comment]
But in that case you don't need/want to install even headers, do you?

**Comment by plummer86** [comment]
Sorry, I was kind of skipping a step. I am using yocto as my build system. I need the headers installed into the sysroot used to cross compile other applications that use libnetconf. Creating the install target to install just the library and headers gets what I need into the sysroot. But no, the headers don't actually go on the product.

**Comment by rkrejci** [comment]
I still don't see the reason to separate headers and other devel-tools.  It just complicates the configure script and 99% of users will use them together. Note that even the files you are separating from headers can be used to create an application based on libnetconf - pkgconfig is used to get necessary options for compiler, etc. Separating these files is not a good idea.

**Pull request closed without merging**
