### PR TITLE
Fix issue #171

### PR DESCRIPTION
**Pull request by andre-brizido**
Multiple augments of the same node within a YIN/YANG module were not being processed correctly

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi,
have you tested the code, does it work for you? The idea seems good to me, but `xmlNodeGetContent` always returned an empty string for some reason when I tried it and in effect only the first augment was applied.

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi

Yes, I have tested the code and it works for me. But I think I already know what the problem is.
I didn't read the manual of  xmlNodeGetContent carefully enough. It seems that it returns the text context of a node or the aggregate string of the values carried by the node's childs. 
Probably the model that you used for testing does not have any description node (which is a texto node) as child of an augment.
This also works for me and I think it solves the problem correctly:

```
   switch (type) {
   case 1: /* augment */

      //we must add the attributes to the candidate node before comparing
      node = xmlCopyNode(nodes->nodesetval->nodeTab[i], 1);
      ns = xmlNewNs(node, BAD_CAST "libnetconf", BAD_CAST "libnetconf");
      xmlSetNsProp(node, ns, BAD_CAST "module", BAD_CAST model_name);
      xmlSetNsProp(node, ns, BAD_CAST "ns", BAD_CAST model_ns);

      /* check whether this augment was not already resolved */
      for (node_aux = path_node->children; node_aux != NULL; node_aux = node_aux->next) {
         if (xmlStrcmp(node_aux->name, BAD_CAST "augment") == 0) {
            resolved_path = (char*) xmlGetProp (node_aux, BAD_CAST "target-node");
            resolved_ns = (char*) xmlGetNsProp (node_aux, BAD_CAST "ns", BAD_CAST "libnetconf");
            if (strcmp(to_resolve_path, resolved_path) == 0 && strcmp(model_ns, resolved_ns) == 0) {
               xmlBufferPtr content1 = xmlBufferCreate(), content2 = xmlBufferCreate();

               //The same module can have multiple augment statetements of the same node.
               //The only way to check if it has already been processed is to check the contents.
               if (content1 && content2)
               {
                  xmlNodeDump(content1, node_aux->doc, node_aux, 0, 0);
                  xmlNodeDump(content2, node->doc,  node, 0, 0);
                  if (xmlStrcmp(xmlBufferContent(content1), xmlBufferContent(content2)) == 0) {
                     xmlBufferFree(content1);
                     xmlBufferFree(content2);
                     free(resolved_path);
                     free(resolved_ns);
                     break;
                  }
               }

               xmlBufferFree(content1);
               xmlBufferFree(content2);
            }
            free(resolved_path);
            free(resolved_ns);
         }
      }

      if (node_aux != NULL) {
         /* already resolved, discard the copy node */
         xmlUnlinkNode(node);
         xmlFreeNode(node);
         break;
      }

      xmlAddChild(path_node, node);

      /*
       * if the model is connected with the transAPI module, add it to the
       * list of transAPI modules of the datastore
       */
      if (path_type == 0 && aug_transapi != NULL) {
         ncds_transapi_enlink(ds, aug_transapi);
      }

      /* remember the change */
      ret = 1;
      break;
   case 2: /* refine */

```
            
Should I make another pull request?

Regards
Andre

**Comment by michalvasko** [comment]
Hi Andre,
yes, please make another pull request and meanwhile I will test it.

Regards,
Michal

**Comment by andre-brizido** [comment]
Leave a comment

**Comment by andre-brizido** [comment]
Hi Michal

I've made the commits. I didn't notice that the pull request was automatically updated.

Regards
Andre

**Comment by michalvasko** [comment]
Hi Andre,
thanks, what I tested a week ago worked well.

Regards,
Michal

**Pull request merged**
